ja:
  activerecord:
    models:
      inscontract: '契約'
      claim: '保険金請求'
      product: '契約種類'
    attributes:
      inscontract:
        id: '契約番号'
        member_id: '契約者ID'
        inception_datetime_at: '契約開始日'
        expiry_datetime_at: '契約終了日'
        product_id: '契約種類'
        premium: '掛け金（円）'
        created_at: '申込日'
        updated_at: '更新日'
      claim:
        id: '請求番号'
        member_id: '契約者ID'
        claim_datetime_at: '事故日'
        image: '事故画像'
        description: '事故に関する記載'
        claim_amount: '保険金請求額（円）'
        product_id: '契約種類'
        state: '処理状況'
        created_at: '請求日'
        updated_at: '更新日'
      product:
        premium: '掛け金（円）'
